name: Node.js CI/CD

on:
  push:
    branches:
      - master # Replace "main" with your default branch if different

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
#    - name: Install dependencies
#      run: npm ci

#    - name: Run tests
#      run: npm test

    - name: Build application
      run: npm run build 

    - name: Deploy to server
      run: |
        ssh upload@10.10.73.230 "mkdir app"
        rsync -avz --delete --exclude '.git*' --exclude 'node_modules' ./ upload@10.10.73.230:/home/app
        ssh user@10.10.73.230 "cd app && npm install --production && pm2 start index.js"
#      env:
#        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
